=== ArrayIterator/gettext-l10n/src/Schema/translation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:annotation>
        <xs:documentation>
            The Gettext XML Schema is used to validate the structure of a Gettext translation file.
        </xs:documentation>
    </xs:annotation>

    <!-- attribute flags -->
    <xs:complexType name="FlagsType">
        <xs:sequence>
            <xs:element name="item" type="xs:string" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>The flags used to mark the translation file. The flag is case-insensitive.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([a-z]+([a-z-]*[a-z]+)?|range:\s*([0-9]+-[0-9]+)?)\s*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- attribute references -->
    <xs:complexType name="ReferencesType">
        <xs:sequence>
            <xs:element name="item" type="xs:string" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>The references used to identify the original source of the translations.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="^[^:]+(:(?:0|[1-9][0-9]*))?"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- attribute comments -->
    <xs:complexType name="CommentsType">
        <xs:sequence>
            <xs:element name="item" type="xs:string" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>The comments used to provide additional information about the translation file.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- start translation / root -->
    <xs:element name="translation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flags" type="FlagsType" minOccurs="0">
                    <xs:unique name="translationUniqueFlag">
                        <xs:selector xpath="item"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                </xs:element>
                <xs:element name="references" type="ReferencesType" minOccurs="0"/>
                <xs:element name="comments" type="CommentsType" minOccurs="0"/>
                <xs:element name="extracted-comments" type="CommentsType" minOccurs="0"/>
                <xs:element name="headers" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="project-id-version" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The project-id-version key is the name and version of the project.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="creation-date" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The pot-creation-date key is the date and time when the POT file was created.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="revision-date" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The po-revision-date key is the date and time when the PO file was last revised.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="last-translator" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The last-translator key is the name and email address of the last translator.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="language-team" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The language-team key is the language and email address of the translation team.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="language" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>The language key is the language code of the translation.</xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z]+([a-zA-Z0-9_-]*[a-zA-Z0-9])?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="mime-version" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The mime-version key is the MIME version of the translation file.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="content-type" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The content-type key is the content type of the translation file.</xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="text/plain\s*;\s*charset=\s*([a-zA-Z0-9_-]+)\s*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="content-transfer-encoding" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The content-transfer-encoding key is the content transfer encoding of the translation file.</xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="7bit"/>
                                        <xs:enumeration value="8bit"/>
                                        <xs:enumeration value="quoted-printable"/>
                                        <xs:enumeration value="base64"/>
                                        <xs:enumeration value="binary"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="plural-forms" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The plural-forms key is the plural forms of the translation file.</xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\s*nplurals=\s*([0-9]+)\s*;\s*plural=\s*([^;]+)\s*;?\s*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="header" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="name" type="xs:NCName" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="uniqueHeaderKey">
                        <xs:selector xpath="header"/>
                        <xs:field xpath="@key"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="translations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="context" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>The context of the translation file.</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="item" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="comments" type="CommentsType" minOccurs="0"/>
                                                    <xs:element name="extracted-comments" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="comment" type="xs:string" maxOccurs="unbounded"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="references" type="ReferencesType" minOccurs="0"/>
                                                    <xs:element name="flags" type="FlagsType" minOccurs="0">
                                                        <xs:unique name="translationsUniqueFlag">
                                                            <xs:selector xpath="item"/>
                                                            <xs:field xpath="."/>
                                                        </xs:unique>
                                                    </xs:element>
                                                    <xs:choice>
                                                        <xs:element name="enable" minOccurs="0"/>
                                                        <xs:element name="disabled" minOccurs="0"/>
                                                    </xs:choice>
                                                    <xs:element name="msgid" type="xs:string"/>
                                                    <xs:element name="msgid_plural" type="xs:string" minOccurs="0"/>
                                                    <xs:element name="msgstr">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="item" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" use="required">
                                        <xs:annotation>
                                            <xs:documentation>The name of the context.</xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <!-- attributes -->
            <xs:attribute name="revision" type="xs:integer" default="0" xml:space="preserve">
                <xs:annotation>
                    <xs:documentation>The revision number of the translation file.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ArrayIterator/gettext-l10n/examples/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<translation
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../src/Schema/translation.xsd"
        revision="1"
>
    <flags>
        <item>fuzzy</item>
        <item>c-format</item>
    </flags>
    <references>
        <item>src/file.js:10</item>
    </references>
    <comments>
        <item>This is a comment about the translation file.</item>
    </comments>
    <extracted-comments>
        <item>This is an extracted comment about the translation file.</item>
    </extracted-comments>
    <headers>
        <project-id-version>My Project 1.0</project-id-version>
        <creation-date>2023-10-01 12:00+0000</creation-date>
        <revision-date>2023-10-01 12:00+0000</revision-date>
        <last-translator>John Doe &lt;john.doe@example.com&gt;</last-translator>
        <language>id</language>
        <language-name>Bahasa Indonesia</language-name>
        <language-team>Indonesia &lt;en@example.com&gt;</language-team>
        <mime-version>1.0</mime-version>
        <content-type>text/plain; charset=UTF-8</content-type>
        <content-transfer-encoding>8bit</content-transfer-encoding>
        <plural-forms>nplurals=2; plural=(n != 1);</plural-forms>
        <custom-header>
            <item name="custom-header">Custom Header</item>
            <item name="custom-header2">Custom Header 2</item>
        </custom-header>
    </headers>
    <translations>
        <context name="">
            <item>
                <comments>
                    <item>This is a comment for the translator as a string.</item>
                </comments>
                <disabled/>
                <msgid>as a key reference</msgid>
                <msgid_plural/>
                <msgstr>
                    <item>sebagai referensi kunci</item>
                </msgstr>
            </item>
            <item>
                <comments/>
                <references/>
                <flags/>
                <msgid/>
                <msgid_plural>Hello, worlds!</msgid_plural>
                <msgstr>
                    <item>Halo, dunia!</item>
                    <item>Halo, dunia!</item>
                </msgstr>
            </item>
            <item>
                <comments>
                    <item>the key is the msgid</item>
                    <item>the key will ignore or just be as a key reference</item>
                </comments>
                <references>
                    <item>src/file.js:10</item>
                </references>
                <flags>
                    <item>fuzzy</item>
                </flags>
                <msgid>The Cat</msgid>
                <msgid_plural>The Cats</msgid_plural>
                <msgstr>
                    <item>Kucing</item>
                    <item>Kucing</item>
                </msgstr>
            </item>
            <item>
                <comments>
                    <item>this translation is disabled or just as commented translation like po file with: #~ msgid
                        "Hello, world!"
                    </item>
                </comments>
                <references>
                    <item>src/file.js:10</item>
                </references>
                <flags>
                    <item>fuzzy</item>
                </flags>
                <enable>false</enable>
                <msgid>Hello, world!</msgid>
                <msgstr>
                    <item>Halo, dunia!</item>
                </msgstr>
            </item>
        </context>
    </translations>
</translation>
